output_name: printables
save_strategy: csv 

pagination: False

enrich: False
# enrich_column: ean

base_url: https://www.printables.com/store 
start_page: 1
end_page: 1
link_base: https://www.printables.com

field_selectors:
  title: a.h
  link: a.h[href]
  price: span.svelte-1jkasgf

# enrich_selectors: 
#   - dd.specs__value
